Web/Models/ErrorViewModel.cs
using System;

namespace MercuryHealthCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MercuryHealthCore.lib.Repositories;
using MercuryHealthCore.lib.DomainModel;

namespace MercuryHealthCore.Controllers
{
    public class ExerciseController : Controller
    {
        private IExerciseRepository _exerciseRepo;
        public ExerciseController(IExerciseRepository exerciseRepo) {
            _exerciseRepo = exerciseRepo;
        }

        public IActionResult Index()
        {
            var allExercises = _exerciseRepo.GetExercises();
            return View(allExercises);
        }

        public IActionResult Edit(Guid id) {
            var exerciseObj = _exerciseRepo.GetExercise(id);
            return View(exerciseObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Exercise exercise) {
            if(ModelState.IsValid) {
                _exerciseRepo.SaveExercise(exercise);
                _exerciseRepo.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid id) {
            var exerciseObj = _exerciseRepo.GetExercise(id);
            return View(exerciseObj);
        }

        public IActionResult Delete(Guid id) {
            var exerciseObj = _exerciseRepo.GetExercise(id);
            return View(exerciseObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Exercise exercise) {
            _exerciseRepo.DeleteExercise(exercise.Id);
            _exerciseRepo.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Exercise exercise) {
            _exerciseRepo.SaveExercise(exercise);
            _exerciseRepo.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MercuryHealthCore.Models;

namespace MercuryHealthCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/NutritionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MercuryHealthCore.lib.Repositories;
using MercuryHealthCore.lib.DomainModel;

namespace MercuryHealthCore.Controllers
{
    public class NutritionController : Controller
    {
        private INutritionRepository _nutritionRepo;
        public NutritionController(INutritionRepository nutritionRepo) {
            _nutritionRepo = nutritionRepo;
        }

        public IActionResult Index()
        {
            var allFood = _nutritionRepo.GetFoodLogEntries();
            return View(allFood);
        }

        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FoodLogEntry food) {
            _nutritionRepo.SaveFoodLogEntry(food);
            _nutritionRepo.SaveChanges();

            return RedirectToAction("Index");

        }

        public IActionResult Delete(int id){
            var dataObj = _nutritionRepo.GetFoodLogEntry(id);
            return View(dataObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(FoodLogEntry food) {
            _nutritionRepo.DeleteFoodLogEntry(food.Id);
            _nutritionRepo.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id) {
            var dataObj = _nutritionRepo.GetFoodLogEntry(id);
            return View(dataObj);
        }

        public IActionResult Edit(int id) {
            var dataObj = _nutritionRepo.GetFoodLogEntry(id);
            return View(dataObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(FoodLogEntry food) {
            _nutritionRepo.SaveFoodLogEntry(food);
            _nutritionRepo.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Web/Views/Exercise/Create.cshtml
@model MercuryHealthCore.lib.DomainModel.Exercise

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.VideoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.MusclesInvolved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MusclesInvolved, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MusclesInvolved, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Equipment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Equipment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Equipment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web/Views/Exercise/Delete.cshtml
@model MercuryHealthCore.lib.DomainModel.Exercise

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exercise</h4>
    <hr />
    @Html.HiddenFor(model => model.Id)
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MusclesInvolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MusclesInvolved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Equipment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/Exercise/Details.cshtml
@model MercuryHealthCore.lib.DomainModel.Exercise

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Exercise</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MusclesInvolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MusclesInvolved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Equipment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Web/Views/Exercise/Edit.cshtml
@model MercuryHealthCore.lib.DomainModel.Exercise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.VideoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.MusclesInvolved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MusclesInvolved, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MusclesInvolved, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Equipment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Equipment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Equipment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web/Views/Exercise/Index.cshtml
@model IEnumerable<MercuryHealthCore.lib.DomainModel.Exercise>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VideoUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MusclesInvolved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Equipment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VideoUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MusclesInvolved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Equipment)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="HeaderBackground">
    <h1><span id="HomePageTitle">Mercury Health Group</span></h1>
 
    <p>The mission of Mercury Health Group is to help you improve your longevity and your quality of life through healthy activity.</p>
        &nbsp;&nbsp;&nbsp;<a href="/FoodLogEntries/Create" class="abel-button btn btn-primary btn-large">Make healthy choices, create a nutrition item now &raquo;&raquo;&raquo;</a>
        <br />
        &nbsp;&nbsp;&nbsp;<a href="/Exercises/Create" class="btn btn-primary btn-large">Physical activity boosts mental wellness, create an exercise entry now &raquo;&raquo;&raquo;</a>
        <br /><br />
</div>


<div class="">
    <h1 class="text-center display-4">Welcome To The Mercury Health Family</h1>
    <p>Welcome to Mercury Health. Where your health is our business.
    </p>
</div>

    <div class="row">
        <div class="col-md-4">
            <h2>Exercise</h2>
            <p>
                Physical activity is an important part of a healthy lifestyle. Our advanced tracking
                tools enable two-way auto syncing with all the popular activity trackers.
            </p>
        </div>
        <div class="col-md-4">
            <h2>Nutrition</h2>
            <p>
                A well crafted diet can help you accomplish your health goals. Start logging all your meals with
                our logging tools. Our tools combine the power of AI to enable food and activity loggin faster and easier
                for a healtier life.
            </p>
        </div>
    </div>

Web/Views/Nutrition/Create.cshtml
@model MercuryHealthCore.lib.DomainModel.FoodLogEntry

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FoodLogEntry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.MealTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MealTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MealTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.ProteinInGrams, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProteinInGrams, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProteinInGrams, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.FatInGrams, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatInGrams, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatInGrams, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.CarbohydratesInGrams, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarbohydratesInGrams, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarbohydratesInGrams, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.SodiumInGrams, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SodiumInGrams, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SodiumInGrams, "", new { @class = "text-danger" })
            </div>
        </div>
        

        @*<div class="form-group abel-editgroup">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group abel-editgroup">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web/Views/Nutrition/Delete.cshtml
@model MercuryHealthCore.lib.DomainModel.FoodLogEntry

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FoodLogEntry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MealTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MealTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tags)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProteinInGrams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProteinInGrams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatInGrams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatInGrams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarbohydratesInGrams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarbohydratesInGrams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SodiumInGrams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SodiumInGrams)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mercury Health Group</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mercury Health Group</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercise" asp-action="Index">Exercise</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nutrition" asp-action="Index">Nutrition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">My Metrics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Mercury Health Group - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>